NASUX_PKG_HOMEPAGE=https://gitlab.gnome.org/GNOME/adwaita-icon-theme
NASUX_PKG_DESCRIPTION="GNOME standard icons"
NASUX_PKG_LICENSE="LGPL-3.0"
NASUX_PKG_MAINTAINER="@nastech-ai"
NASUX_PKG_VERSION="50.0"
NASUX_PKG_SRCURL=https://download.gnome.org/sources/adwaita-icon-theme/${NASUX_PKG_VERSION%.*}/adwaita-icon-theme-${NASUX_PKG_VERSION}.tar.xz
NASUX_PKG_SHA256=fac6e0401fca714780561a081b8f7e27c3bc1db34ebda4da175081f26b24d460
TERMUX_PKG_PLATFORM_INDEPENDENT=true
TERMUX_PKG_AUTO_UPDATE=true
NASUX_PKG_DEPENDS="adwaita-icon-theme-legacy, hicolor-icon-theme"
TERMUX_PKG_RM_AFTER_INSTALL="share/icons/Adwaita/icon-theme.cache"
