NASUX_PKG_HOMEPAGE=https://www.kde.org/
NASUX_PKG_DESCRIPTION="Set of item models extending the Qt model-view framework (KDE)"
NASUX_PKG_LICENSE="LGPL-2.1"
NASUX_PKG_MAINTAINER="@nastech-ai"
NASUX_PKG_VERSION="5.116.0"
NASUX_PKG_SRCURL="https://download.kde.org/stable/frameworks/${NASUX_PKG_VERSION%.*}/kitemmodels-${NASUX_PKG_VERSION}.tar.xz"
NASUX_PKG_SHA256=537cee9bbadf5471e5217e48605adbf941335de45f0041e7d5a31422e4b49ff1
TERMUX_PKG_AUTO_UPDATE=false
NASUX_PKG_DEPENDS="libc++, qt5-qtbase, qt5-qtdeclarative"
TERMUX_PKG_BUILD_DEPENDS="extra-cmake-modules, qt5-qtbase-cross-tools, qt5-qtdeclarative-cross-tools"
