NASUX_PKG_HOMEPAGE=https://github.com/libpinyin/ibus-libpinyin
NASUX_PKG_DESCRIPTION="Intelligent Pinyin engine based on libpinyin for IBus"
NASUX_PKG_LICENSE="GPL-3.0"
NASUX_PKG_MAINTAINER="@nastech-ai"
NASUX_PKG_VERSION=1.16.5
TERMUX_PKG_REVISION=1
NASUX_PKG_SRCURL=https://github.com/libpinyin/ibus-libpinyin/releases/download/$NASUX_PKG_VERSION/ibus-libpinyin-$NASUX_PKG_VERSION.tar.gz
NASUX_PKG_SHA256=cc652d48e68b8b03afc5e9e08509676aee89f9d492b9a3897cd028bcc800ce31
NASUX_PKG_BUILD_IN_SRC=true
NASUX_PKG_DEPENDS="ibus, libpinyin, libopencc, libsqlite, lua51, libdb"
