NASUX_PKG_HOMEPAGE="https://github.com/baskerville/bspwm"
NASUX_PKG_DESCRIPTION="A tiling window manager based on binary space partitioning"
NASUX_PKG_LICENSE="BSD 2-Clause"
NASUX_PKG_MAINTAINER="@nastech-ai"
NASUX_PKG_VERSION="0.9.12"
NASUX_PKG_SRCURL="https://github.com/baskerville/bspwm/archive/refs/tags/$NASUX_PKG_VERSION.tar.gz"
NASUX_PKG_SHA256=ca3be808e3d0c785955f1613e6e860fc51b5db086b821b48707466da1a06392c
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_UPDATE_TAG_TYPE="newest-tag"
NASUX_PKG_DEPENDS="libxcb, sxhkd, xcb-util, xcb-util-keysyms, xcb-util-wm"
NASUX_PKG_BUILD_IN_SRC=true
