NASUX_PKG_HOMEPAGE=https://lxqt.github.io
NASUX_PKG_DESCRIPTION="GUI to query passwords on behalf of SSH agents"
NASUX_PKG_LICENSE="LGPL-2.1"
NASUX_PKG_MAINTAINER="@nastech-ai"
NASUX_PKG_VERSION="2.4.0"
NASUX_PKG_SRCURL="https://github.com/lxqt/lxqt-openssh-askpass/releases/download/${NASUX_PKG_VERSION}/lxqt-openssh-askpass-${NASUX_PKG_VERSION}.tar.xz"
NASUX_PKG_SHA256=1a4d5c9c9450cc08cacd1646fc55dc9c78c297ab1fbae49b8047df78665b5c55
NASUX_PKG_DEPENDS="libc++, liblxqt, qt6-qtbase"
TERMUX_PKG_BUILD_DEPENDS="lxqt-build-tools, qt6-qttools"
TERMUX_PKG_AUTO_UPDATE=true
