NASUX_PKG_HOMEPAGE=https://github.com/holman/spark
NASUX_PKG_DESCRIPTION="▁▂▃▅▂▇ in your shell"
NASUX_PKG_LICENSE="MIT"
NASUX_PKG_MAINTAINER="@nastech-ai"
NASUX_PKG_VERSION=1.0.1
NASUX_PKG_SRCURL=$NASUX_PKG_HOMEPAGE/archive/v$NASUX_PKG_VERSION.tar.gz
NASUX_PKG_SHA256=a81c1bc538ce8e011f62264fe6f33d28042ff431b510a6359040dc77403ebab6
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_UPDATE_TAG_TYPE="newest-tag"
NASUX_PKG_BUILD_IN_SRC=true
NASUX_PKG_DEPENDS=bash
TERMUX_PKG_PLATFORM_INDEPENDENT=true

termux_step_make_install() {
	local bin="$(basename $NASUX_PKG_HOMEPAGE)"
	install -D "$bin" -t "$TERMUX_PREFIX/bin"
}
