NASUX_PKG_HOMEPAGE=https://github.com/AyatanaIndicators/libayatana-indicator
NASUX_PKG_DESCRIPTION="Ayatana Indicators Shared Library"
NASUX_PKG_LICENSE="GPL-3.0"
NASUX_PKG_MAINTAINER="@nastech-ai"
NASUX_PKG_VERSION="0.9.5"
NASUX_PKG_SRCURL=https://github.com/AyatanaIndicators/libayatana-indicator/archive/refs/tags/${NASUX_PKG_VERSION}.tar.gz
NASUX_PKG_SHA256=73d71c908b803f12e4a5ecd8392511b58afbdd0c82ad7909611a17bb7847c5c8
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_UPDATE_TAG_TYPE="newest-tag"
NASUX_PKG_DEPENDS="ayatana-ido, gdk-pixbuf, glib, gtk3"
