NASUX_PKG_HOMEPAGE=https://mate-desktop.org/
NASUX_PKG_DESCRIPTION="Set of backgrounds packaged with the MATE desktop"
NASUX_PKG_LICENSE="GPL-2.0-or-later"
NASUX_PKG_MAINTAINER="@nastech-ai"
NASUX_PKG_VERSION="1.28.0"
NASUX_PKG_SRCURL="https://github.com/mate-desktop/mate-backgrounds/releases/download/v$NASUX_PKG_VERSION/mate-backgrounds-$NASUX_PKG_VERSION.tar.xz"
NASUX_PKG_SHA256=50d1afd02486bd07ac22a5a6b6efa3031148f0d48a82e488d909ad57003a6943
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_BUILD_DEPENDS="mate-common"
TERMUX_PKG_PLATFORM_INDEPENDENT=true
