NASUX_PKG_HOMEPAGE=https://www.raylib.com/
NASUX_PKG_DESCRIPTION="A simple and easy-to-use library to enjoy videogames programming"
NASUX_PKG_LICENSE="ZLIB"
NASUX_PKG_MAINTAINER="@nastech-ai"
NASUX_PKG_VERSION=6.0
NASUX_PKG_SRCURL="https://github.com/raysan5/raylib/archive/refs/tags/${NASUX_PKG_VERSION}.tar.gz"
NASUX_PKG_SHA256=2b3ee1e2120c7a0796b33062c7e9a694dd8a8caa56a96319ac8c8ecf54a90d0b
NASUX_PKG_DEPENDS="glfw"
TERMUX_PKG_BUILD_DEPENDS="glu, opengl"
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
-DPLATFORM=Desktop
-DBUILD_EXAMPLES=OFF
-DBUILD_SHARED_LIBS=ON
-DUSE_EXTERNAL_GLFW=ON
-DOPENGL_VERSION=2.1
"
