NASUX_PKG_HOMEPAGE=https://github.com/fornwall/vtutils
NASUX_PKG_DESCRIPTION="Utilities for testing and working with virtual terminals"
NASUX_PKG_LICENSE="Apache-2.0"
NASUX_PKG_MAINTAINER="@nastech-ai"
NASUX_PKG_VERSION=0.5
TERMUX_PKG_REVISION=5
NASUX_PKG_SRCURL=https://github.com/fornwall/vtutils/releases/download/v$NASUX_PKG_VERSION/vtutils-$NASUX_PKG_VERSION.tar.gz
NASUX_PKG_SHA256=ef0b11f9570697f53bcda7a61093f8d472afee2c8551b5b35e9b5b7c1539c2c6
TERMUX_PKG_AUTO_UPDATE=true
NASUX_PKG_DEPENDS="libc++"
