NASUX_PKG_HOMEPAGE=https://mate-session-manager.mate-desktop.dev/
NASUX_PKG_DESCRIPTION="mate-session contains the MATE session manager, as well as a configuration program to choose applications starting on login."
NASUX_PKG_LICENSE="GPL-2.0"
NASUX_PKG_MAINTAINER="@nastech-ai"
NASUX_PKG_VERSION="1.28.0"
TERMUX_PKG_REVISION=1
NASUX_PKG_SRCURL=https://github.com/mate-desktop/mate-session-manager/releases/download/v$NASUX_PKG_VERSION/mate-session-manager-$NASUX_PKG_VERSION.tar.xz
NASUX_PKG_SHA256=d32ce4595ba1da65290777203f2bc82bd973b214a3a04080a1ef5c68990a2d7b
TERMUX_PKG_AUTO_UPDATE=true
NASUX_PKG_DEPENDS="dbus, dbus-glib, gdk-pixbuf, glib, gtk3, libcairo, libepoxy, libice, libsm, libx11, libxau, libxcomposite, libxext, libxrender, libxtst, opengl"
