NASUX_PKG_HOMEPAGE=https://lxqt.github.io
NASUX_PKG_DESCRIPTION="A library to query system information"
NASUX_PKG_LICENSE="LGPL-2.1"
NASUX_PKG_MAINTAINER="@nastech-ai"
NASUX_PKG_VERSION="1.1.0"
TERMUX_PKG_REVISION=1
NASUX_PKG_SRCURL="https://github.com/lxqt/libsysstat/releases/download/${NASUX_PKG_VERSION}/libsysstat-${NASUX_PKG_VERSION}.tar.xz"
NASUX_PKG_SHA256=996e5e8c43b1364a81a660b56956948c628e919f1d73554df6be152bbec8d430
NASUX_PKG_DEPENDS="libc++, qt6-qtbase"
TERMUX_PKG_BUILD_DEPENDS="lxqt-build-tools"
TERMUX_PKG_AUTO_UPDATE=true
