NASUX_PKG_HOMEPAGE=https://gitlab.freedesktop.org/xorg/util/bdftopcf
NASUX_PKG_DESCRIPTION="convert X font from Bitmap Distribution Format to Portable Compiled Format"
NASUX_PKG_LICENSE="HPND"
NASUX_PKG_MAINTAINER="@nastech-ai"
NASUX_PKG_VERSION="1.1.2"
TERMUX_PKG_REVISION=1
NASUX_PKG_SRCURL=https://xorg.freedesktop.org/archive/individual/util/bdftopcf-${NASUX_PKG_VERSION}.tar.xz
NASUX_PKG_SHA256=bc60be5904330faaa3ddd2aed7874bee2f29e4387c245d6787552f067eb0523a
TERMUX_PKG_AUTO_UPDATE=true
NASUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_BUILD_DEPENDS="xorgproto"
