NASUX_PKG_HOMEPAGE=https://salsa.debian.org/iso-codes-team/iso-codes
NASUX_PKG_DESCRIPTION="Lists of the country, language, and currency names"
NASUX_PKG_LICENSE="LGPL-2.1"
NASUX_PKG_MAINTAINER="@nastech-ai"
NASUX_PKG_VERSION="4.20.1"
NASUX_PKG_SRCURL=https://salsa.debian.org/iso-codes-team/iso-codes/-/archive/v${NASUX_PKG_VERSION}/iso-codes-v${NASUX_PKG_VERSION}.tar.gz
NASUX_PKG_SHA256=2d7d9f6084ab9ce6c534ce71a3dd5144b6e474f3c97616459a88f73f44a64bff
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_UPDATE_TAG_TYPE=newest-tag
TERMUX_PKG_PLATFORM_INDEPENDENT=true
