NASUX_PKG_HOMEPAGE=https://github.com/fornwall/utfdecode
NASUX_PKG_DESCRIPTION="Tool for decoding, encoding and debugging unicode"
NASUX_PKG_LICENSE="Apache-2.0"
NASUX_PKG_MAINTAINER="@nastech-ai"
NASUX_PKG_VERSION=0.3.4
TERMUX_PKG_REVISION=7
NASUX_PKG_SRCURL=https://github.com/fornwall/utfdecode/releases/download/v$NASUX_PKG_VERSION/utfdecode-$NASUX_PKG_VERSION.tar.gz
NASUX_PKG_SHA256=5fd1473f6cf6bdedeb33569c3b0f6823aceda366c714f6a475e2d28767f99b5a
NASUX_PKG_DEPENDS="libc++"
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_UPDATE_TAG_TYPE="newest-tag" # As of 2022-11-29T12:17:41 no github releases are available.
