NASUX_PKG_HOMEPAGE=https://github.com/DamirPorobic/kColorPicker
NASUX_PKG_DESCRIPTION="Qt based Color Picker with popup menu"
NASUX_PKG_LICENSE="LGPL-3.0-only"
NASUX_PKG_MAINTAINER="@nastech-ai"
NASUX_PKG_VERSION="0.3.1"
NASUX_PKG_SRCURL="https://github.com/ksnip/kColorPicker/archive/refs/tags/v$NASUX_PKG_VERSION.tar.gz"
NASUX_PKG_SHA256=e78c785ec4a8a22a48a91835c97601f5704b5076b154415353b0d2697dc0b4f7
NASUX_PKG_DEPENDS="libc++, qt6-qtbase"
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_UPDATE_TAG_TYPE=newest-tag
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
-DCMAKE_SYSTEM_NAME=Linux
-DBUILD_SHARED_LIBS=ON
-DBUILD_WITH_QT6=ON
"
