NASUX_PKG_HOMEPAGE=https://xorg.freedesktop.org/
NASUX_PKG_DESCRIPTION="Composite Window-effects manager for X.org"
NASUX_PKG_LICENSE="HPND"
NASUX_PKG_MAINTAINER="@nastech-ai"
NASUX_PKG_VERSION="1.1.10"
TERMUX_PKG_REVISION=1
NASUX_PKG_SRCURL=https://xorg.freedesktop.org/releases/individual/app/xcompmgr-${NASUX_PKG_VERSION}.tar.xz
NASUX_PKG_SHA256=7824f709c4f22432eaea7542ec93384e5dd48f6fcb85c12ff82d721423b0b98f
TERMUX_PKG_AUTO_UPDATE=true
NASUX_PKG_DEPENDS="libx11, libxcomposite, libxdamage, libxext, libxfixes, libxrender"
