NASUX_PKG_HOMEPAGE=https://github.com/tibirna/qgit
NASUX_PKG_DESCRIPTION="A git GUI viewer"
NASUX_PKG_LICENSE="GPL-2.0"
NASUX_PKG_MAINTAINER="@nastech-ai"
NASUX_PKG_VERSION="2.13"
NASUX_PKG_SRCURL=https://github.com/tibirna/qgit/archive/refs/tags/qgit-${NASUX_PKG_VERSION}.tar.gz
NASUX_PKG_SHA256=9fa64b011963b7b876b8634b140ec5339a81a422317df71b619fcee5740a364a
TERMUX_PKG_AUTO_UPDATE=true
NASUX_PKG_DEPENDS="git, libc++, qt6-qtbase, qt6-qt5compat"
TERMUX_PKG_RECOMMENDS="hicolor-icon-theme"
TERMUX_PKG_BUILD_DEPENDS="qt6-qtbase-cross-tools"
NASUX_PKG_BUILD_IN_SRC=true
