NASUX_PKG_HOMEPAGE=http://joewing.net/projects/jwm/
NASUX_PKG_DESCRIPTION="Joe's Window Manager is a light-weight X11 window manager"
NASUX_PKG_LICENSE="MIT"
NASUX_PKG_MAINTAINER="Joshua Kahn <tom@nasux.dev>"
NASUX_PKG_VERSION="2.4.6"
TERMUX_PKG_REVISION=1
NASUX_PKG_SRCURL=https://github.com/joewing/jwm/releases/download/v${NASUX_PKG_VERSION}/jwm-${NASUX_PKG_VERSION}.tar.xz
NASUX_PKG_SHA256=b5871ec28317594b3fa22b83ed5524cc911d498c455eaab3ae68def195dd802d
NASUX_PKG_DEPENDS="libcairo, libjpeg-turbo, libpng, librsvg, libxext, libxinerama, libxmu, libxpm, libxrender, pango"
NASUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_AUTO_UPDATE=true
