NASUX_PKG_HOMEPAGE=https://xorg.freedesktop.org/
NASUX_PKG_DESCRIPTION="X11 Xinerama extension library"
NASUX_PKG_LICENSE="MIT"
NASUX_PKG_MAINTAINER="@nastech-ai"
NASUX_PKG_VERSION="1.1.6"
NASUX_PKG_SRCURL=https://xorg.freedesktop.org/releases/individual/lib/libXinerama-${NASUX_PKG_VERSION}.tar.xz
NASUX_PKG_SHA256=d00fc1599c303dc5cbc122b8068bdc7405d6fcb19060f4597fc51bd3a8be51d7
TERMUX_PKG_AUTO_UPDATE=true
NASUX_PKG_DEPENDS="libx11, libxext"
TERMUX_PKG_BUILD_DEPENDS="xorgproto"
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="--enable-malloc0returnsnull"
