NASUX_PKG_HOMEPAGE=https://xorg.freedesktop.org/
NASUX_PKG_DESCRIPTION="X11 font rasterisation library"
NASUX_PKG_LICENSE="MIT"
NASUX_PKG_MAINTAINER="@nastech-ai"
NASUX_PKG_VERSION="2.0.7"
TERMUX_PKG_REVISION=1
NASUX_PKG_SRCURL=https://xorg.freedesktop.org/releases/individual/lib/libXfont2-${NASUX_PKG_VERSION}.tar.xz
NASUX_PKG_SHA256=8b7b82fdeba48769b69433e8e3fbb984a5f6bf368b0d5f47abeec49de3e58efb
NASUX_PKG_DEPENDS="freetype, libfontenc, zlib"
TERMUX_PKG_BUILD_DEPENDS="xorgproto, xorg-util-macros, xtrans"
TERMUX_PKG_AUTO_UPDATE=true
