NASUX_PKG_HOMEPAGE=https://github.com/ib/xarchiver
NASUX_PKG_DESCRIPTION="GTK+ frontend to various command line archivers"
NASUX_PKG_LICENSE="GPL-2.0"
NASUX_PKG_MAINTAINER="@nastech-ai"
NASUX_PKG_VERSION="0.5.4.26"
TERMUX_PKG_REVISION=1
NASUX_PKG_SRCURL="https://github.com/ib/xarchiver/archive/refs/tags/${NASUX_PKG_VERSION}.tar.gz"
NASUX_PKG_SHA256=58e4fb2c1fb8421573a31cf3b4dfec301076d61f48ac5720df632986c87e9573
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_UPDATE_TAG_TYPE="newest-tag"
NASUX_PKG_DEPENDS="gdk-pixbuf, glib, gtk3"
TERMUX_PKG_RECOMMENDS="arj, llvm, bzip2, cpio, gzip, lz4, lzip, lzop, p7zip, tar, unar, unrar, unzip, xz-utils, zip, zstd"
