NASUX_PKG_HOMEPAGE=https://www.opencode.net/trialuser/qt6ct/
NASUX_PKG_DESCRIPTION="Qt 6 Configuration Utility"
NASUX_PKG_LICENSE="BSD 2-Clause"
NASUX_PKG_MAINTAINER="@nastech-ai"
NASUX_PKG_VERSION="0.11"
TERMUX_PKG_REVISION=5
NASUX_PKG_SRCURL="https://www.opencode.net/trialuser/qt6ct/-/archive/${NASUX_PKG_VERSION}/qt6ct-${NASUX_PKG_VERSION}.tar.gz"
NASUX_PKG_SHA256=32cd06cb4e801362676194ec6c3378498c81eb9484c57870fee3f7d5952ebe1f
TERMUX_PKG_AUTO_UPDATE=true
NASUX_PKG_DEPENDS="libc++, qt6-qtbase, qt6-qtsvg"
TERMUX_PKG_BUILD_DEPENDS="qt6-qttools"
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
-DPLUGINDIR=${TERMUX_PREFIX}/lib/qt6/plugins
"
