NASUX_PKG_HOMEPAGE=https://xorg.freedesktop.org/
NASUX_PKG_DESCRIPTION="X11 Composite extension library"
NASUX_PKG_LICENSE="HPND, MIT"
NASUX_PKG_MAINTAINER="@nastech-ai"
NASUX_PKG_VERSION="0.4.7"
NASUX_PKG_SRCURL=https://xorg.freedesktop.org/releases/individual/lib/libXcomposite-${NASUX_PKG_VERSION}.tar.xz
NASUX_PKG_SHA256=8bdf310967f484503fa51714cf97bff0723d9b673e0eecbf92b3f97c060c8ccb
TERMUX_PKG_AUTO_UPDATE=true
NASUX_PKG_DEPENDS="libx11"
TERMUX_PKG_BUILD_DEPENDS="libxfixes, xorgproto, xorg-util-macros"
