NASUX_PKG_HOMEPAGE=https://xorg.freedesktop.org/
NASUX_PKG_DESCRIPTION="Display information utility for X"
NASUX_PKG_LICENSE="MIT"
NASUX_PKG_MAINTAINER="@nastech-ai"
NASUX_PKG_VERSION="1.4.0"
NASUX_PKG_SRCURL=https://xorg.freedesktop.org/archive/individual/app/xdpyinfo-${NASUX_PKG_VERSION}.tar.xz
NASUX_PKG_SHA256=dc1de6e6e091ed46c4837b0ae9811e8182f7be0d2af638cab3e530ff081a48b6
TERMUX_PKG_AUTO_UPDATE=true
NASUX_PKG_DEPENDS="libx11, libxcb, libxcomposite, libxext, libxi, libxinerama, libxrender, libxtst, libxxf86dga, libxxf86vm"
TERMUX_PKG_BUILD_DEPENDS="xorg-util-macros"
