NASUX_PKG_HOMEPAGE=https://xorg.freedesktop.org/
NASUX_PKG_DESCRIPTION="X11 Direct Graphics Access extension library"
NASUX_PKG_LICENSE="MIT"
NASUX_PKG_MAINTAINER="@nastech-ai"
NASUX_PKG_VERSION="1.1.7"
NASUX_PKG_SRCURL=https://xorg.freedesktop.org/releases/individual/lib/libXxf86dga-${NASUX_PKG_VERSION}.tar.xz
NASUX_PKG_SHA256=b3be5b444d324cb6e0f4b5019a4972c99ea336ccb8ab7968eccefecd917ffde6
TERMUX_PKG_AUTO_UPDATE=true
NASUX_PKG_DEPENDS="libx11, libxext"
TERMUX_PKG_BUILD_DEPENDS="xorg-util-macros"
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="--enable-malloc0returnsnull"
