NASUX_PKG_HOMEPAGE=https://tools.suckless.org/dmenu/
NASUX_PKG_DESCRIPTION="Generic menu for X"
NASUX_PKG_LICENSE="MIT"
NASUX_PKG_MAINTAINER="@nastech-ai"
NASUX_PKG_VERSION="5.4"
NASUX_PKG_SRCURL=https://dl.suckless.org/tools/dmenu-$NASUX_PKG_VERSION.tar.gz
NASUX_PKG_SHA256=8fbace2a0847aa80fe861066b118252dcc7b4ca0a0a8f3a93af02da8fb6cd453
TERMUX_PKG_AUTO_UPDATE=true
NASUX_PKG_DEPENDS="dash, fontconfig, libx11, libxft, libxinerama"
TERMUX_PKG_BUILD_DEPENDS="xorgproto"
NASUX_PKG_BUILD_IN_SRC=true
