blank_issues_enabled: true
contact_links:
  - name: Want to add new mirrors or have mirror-related questions?
    url: https://github.com/nastech-ai/NasUX/issues
    about: Visit NasUX main repo issues page
  - name: Want to ask questions about NasUX-Packages?
    url: https://github.com/nastech-ai/NasUX-Packages/discussions
    about: Join GitHub Discussions for NasUX-Packages
