NASUX_PKG_HOMEPAGE=https://bitmath.org/code/mtdev/
NASUX_PKG_DESCRIPTION="A stand-alone library which transforms all variants of kernel MT events to the slotted type B protocol"
NASUX_PKG_LICENSE="MIT"
NASUX_PKG_MAINTAINER="@nastech-ai"
NASUX_PKG_VERSION="1.1.7"
NASUX_PKG_SRCURL=https://bitmath.org/code/mtdev/mtdev-${NASUX_PKG_VERSION}.tar.gz
NASUX_PKG_SHA256=a55bd02a9af4dd266c0042ec608744fff3a017577614c057da09f1f4566ea32c
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_RM_AFTER_INSTALL="bin/mtdev-test"
