NASUX_PKG_HOMEPAGE=https://github.com/realh/roxterm
NASUX_PKG_DESCRIPTION="ROXTerm is a terminal emulator based on the VTE library"
NASUX_PKG_LICENSE="GPL-2.0"
NASUX_PKG_MAINTAINER="@Yisus7u7"
NASUX_PKG_VERSION="3.18.2"
NASUX_PKG_SRCURL=https://github.com/realh/roxterm/archive/refs/tags/$NASUX_PKG_VERSION.tar.gz
NASUX_PKG_SHA256=d20a19abe03798bfc6c9404eb7ce4fbecabf2e1ab527b587aab76d06635a92e7
TERMUX_PKG_AUTO_UPDATE=true
NASUX_PKG_DEPENDS="dbus, dbus-glib, glib, gtk3, libcairo, libvte, pango"
TERMUX_PKG_BUILD_DEPENDS="xsltproc"
NASUX_PKG_BUILD_IN_SRC=true
