NASUX_PKG_HOMEPAGE="https://invent.kde.org/plasma/oxygen-sounds"
NASUX_PKG_DESCRIPTION="The Oxygen Sound Theme by KDE"
NASUX_PKG_LICENSE="LGPL-2.0-or-later"
NASUX_PKG_MAINTAINER="@nastech-ai"
NASUX_PKG_VERSION="6.6.5"
NASUX_PKG_SRCURL="https://download.kde.org/stable/plasma/${NASUX_PKG_VERSION}/oxygen-sounds-${NASUX_PKG_VERSION}.tar.xz"
NASUX_PKG_SHA256=4c648555fe7ccb9bcf46fb0b4452da85c5821201445eb72ec45b5d95e57942f6
TERMUX_PKG_AUTO_UPDATE=true
NASUX_PKG_DEPENDS="libc++"
TERMUX_PKG_BUILD_DEPENDS="extra-cmake-modules"
TERMUX_PKG_PLATFORM_INDEPENDENT=true
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
-DCMAKE_SYSTEM_NAME=Linux
-DKDE_INSTALL_QMLDIR=lib/qt6/qml
-DKDE_INSTALL_QTPLUGINDIR=lib/qt6/plugins
"
