NASUX_PKG_HOMEPAGE=https://gitlab.gnome.org/GNOME/adwaita-icon-theme-legacy
NASUX_PKG_DESCRIPTION="GNOME fallback icons for legacy apps"
NASUX_PKG_LICENSE="LGPL-3.0"
NASUX_PKG_MAINTAINER="@nastech-ai"
NASUX_PKG_VERSION="46.2"
TERMUX_PKG_REVISION=1
NASUX_PKG_SRCURL=https://download.gnome.org/sources/adwaita-icon-theme-legacy/${NASUX_PKG_VERSION%.*}/adwaita-icon-theme-legacy-${NASUX_PKG_VERSION}.tar.xz
NASUX_PKG_SHA256=548480f58589a54b72d18833b755b15ffbd567e3187249d74e2e1f8f99f22fb4
TERMUX_PKG_PLATFORM_INDEPENDENT=true
TERMUX_PKG_AUTO_UPDATE=true
NASUX_PKG_DEPENDS="hicolor-icon-theme"
TERMUX_PKG_RM_AFTER_INSTALL="share/icons/AdwaitaLegacy/icon-theme.cache"
