NASUX_PKG_HOMEPAGE=https://docs.xfce.org/xfce/thunar/archive
NASUX_PKG_DESCRIPTION="This plugin allows one to extract and create archive from inside the Thunar file manager."
NASUX_PKG_LICENSE="LGPL-2.0"
NASUX_PKG_MAINTAINER="@Yisus7u7"
NASUX_PKG_VERSION="0.6.0"
TERMUX_PKG_REVISION=1
NASUX_PKG_SRCURL=https://archive.xfce.org/src/thunar-plugins/thunar-archive-plugin/${NASUX_PKG_VERSION%.*}/thunar-archive-plugin-${NASUX_PKG_VERSION}.tar.xz
NASUX_PKG_SHA256=692708cd047c7a552f2f85fe2ee32f19c7d5be5bf695d0288e8cadf50289db06
TERMUX_PKG_AUTO_UPDATE=true
NASUX_PKG_DEPENDS="glib, gtk3, libxfce4util, thunar"
TERMUX_PKG_RECOMMENDS="file-roller"
