NASUX_PKG_HOMEPAGE=https://github.com/nastech-ai/NasUX-Packages
NASUX_PKG_DESCRIPTION="A metapackage that installs at-spi2-core"
NASUX_PKG_LICENSE="Public Domain"
NASUX_PKG_MAINTAINER="@nastech-ai"
NASUX_PKG_VERSION=2.48.0
TERMUX_PKG_AUTO_UPDATE=false
TERMUX_PKG_SKIP_SRC_EXTRACT=true
NASUX_PKG_DEPENDS="at-spi2-core (>= 2.48.0)"
TERMUX_PKG_METAPACKAGE=true
TERMUX_PKG_PLATFORM_INDEPENDENT=true
