NASUX_PKG_HOMEPAGE='https://invent.kde.org/frameworks/kdbusaddons'
NASUX_PKG_DESCRIPTION='Addons to QtDBus'
NASUX_PKG_LICENSE="LGPL-2.0, LGPL-3.0"
NASUX_PKG_MAINTAINER="@nastech-ai"
NASUX_PKG_VERSION="6.27.0"
NASUX_PKG_SRCURL="https://download.kde.org/stable/frameworks/${NASUX_PKG_VERSION%.*}/kdbusaddons-${NASUX_PKG_VERSION}.tar.xz"
NASUX_PKG_SHA256=9ea3792b2f1c43d5551437260803fdd676c903e2768f4aac4186054e5b22d4ca
NASUX_PKG_DEPENDS="qt6-qtbase"
TERMUX_PKG_BUILD_DEPENDS="extra-cmake-modules (>= ${NASUX_PKG_VERSION%.*}), libc++, qt6-qttools"
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
-DCMAKE_SYSTEM_NAME=Linux
-DKDE_INSTALL_QMLDIR=lib/qt6/qml
-DKDE_INSTALL_QTPLUGINDIR=lib/qt6/plugins
"
