NASUX_PKG_HOMEPAGE=https://xorg.freedesktop.org/
NASUX_PKG_DESCRIPTION="Set the keyboard using the X Keyboard Extension"
NASUX_PKG_LICENSE="HPND"
NASUX_PKG_MAINTAINER="@nastech-ai"
NASUX_PKG_VERSION="1.3.5"
NASUX_PKG_SRCURL="https://xorg.freedesktop.org/releases/individual/app/setxkbmap-${NASUX_PKG_VERSION}.tar.xz"
NASUX_PKG_SHA256=360193cecc93f906d8383a8fb5c1f3a7eed35e6ced0e118a64ee56ae13c88cac
NASUX_PKG_DEPENDS="libx11, libxkbfile, libxrandr"
TERMUX_PKG_AUTO_UPDATE=true
