NASUX_PKG_HOMEPAGE=https://www.kde.org/
NASUX_PKG_DESCRIPTION="Set of item views extending the Qt model-view framework (KDE)"
NASUX_PKG_LICENSE="LGPL-2.1"
NASUX_PKG_MAINTAINER="@nastech-ai"
NASUX_PKG_VERSION="5.116.0"
NASUX_PKG_SRCURL="https://download.kde.org/stable/frameworks/${NASUX_PKG_VERSION%.*}/kitemviews-${NASUX_PKG_VERSION}.tar.xz"
NASUX_PKG_SHA256=6c0efbf408dab60c58bb13bb3a7488827283a5eea947ef3cfd0fbcb4f09e01eb
TERMUX_PKG_AUTO_UPDATE=false
NASUX_PKG_DEPENDS="libc++, qt5-qtbase"
TERMUX_PKG_BUILD_DEPENDS="extra-cmake-modules, qt5-qtbase-cross-tools, qt5-qttools-cross-tools"
