NASUX_PKG_HOMEPAGE="https://www.qt.io"
NASUX_PKG_DESCRIPTION="Qt HTTP Server"
NASUX_PKG_LICENSE="GPL-3.0-only, LGPL-3.0-only"
NASUX_PKG_MAINTAINER="@nastech-ai"
NASUX_PKG_VERSION="6.11.1"
NASUX_PKG_SRCURL="https://download.qt.io/official_releases/qt/${NASUX_PKG_VERSION%.*}/${NASUX_PKG_VERSION}/submodules/qthttpserver-everywhere-src-${NASUX_PKG_VERSION}.tar.xz"
NASUX_PKG_SHA256="04bf70fcf76861f9b6870c728085f2375a6b6d923cb5d1a116dff2ed52a4e706"
TERMUX_PKG_AUTO_UPDATE=true
NASUX_PKG_DEPENDS="libc++, qt6-qtbase, qt6-qtwebsockets"
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
-DCMAKE_SYSTEM_NAME=Linux
"
