NASUX_PKG_HOMEPAGE=https://www.kde.org/
NASUX_PKG_DESCRIPTION="Method collection to manipulate strings using various encodings (KDE)"
NASUX_PKG_LICENSE="LGPL-2.1"
NASUX_PKG_MAINTAINER="@nastech-ai"
NASUX_PKG_VERSION="5.116.0"
NASUX_PKG_SRCURL="https://download.kde.org/stable/frameworks/${NASUX_PKG_VERSION%.*}/kcodecs-${NASUX_PKG_VERSION}.tar.xz"
NASUX_PKG_SHA256=a489d22e91cafcb60854c6e914969e1f3f8270b403baf2ec3a1d76ae2bd3680e
TERMUX_PKG_AUTO_UPDATE=false
NASUX_PKG_DEPENDS="libc++, qt5-qtbase"
TERMUX_PKG_BUILD_DEPENDS="extra-cmake-modules, qt5-qtbase-cross-tools, qt5-qttools-cross-tools"
