NASUX_PKG_HOMEPAGE=https://directory.fsf.org/wiki/Plotutils
NASUX_PKG_DESCRIPTION="Set of utilities and libraries for plotting."
NASUX_PKG_LICENSE="GPL-2.0"
NASUX_PKG_MAINTAINER="@nastech-ai"
NASUX_PKG_VERSION=2.6
TERMUX_PKG_REVISION=33
NASUX_PKG_SRCURL=https://mirrors.kernel.org/gnu/plotutils/plotutils-${NASUX_PKG_VERSION}.tar.gz
NASUX_PKG_SHA256=4f4222820f97ca08c7ea707e4c53e5a3556af4d8f1ab51e0da6ff1627ff433ab
NASUX_PKG_DEPENDS="libice, libpng, libsm, libx11, libxaw, libxext, libxmu, libxt, zlib"
