NASUX_PKG_HOMEPAGE=http://t-sato.in.coocan.jp/xvkbd/
NASUX_PKG_DESCRIPTION="Virtual keyboard for X window system"
NASUX_PKG_LICENSE="GPL-2.0"
NASUX_PKG_MAINTAINER="@nastech-ai"
NASUX_PKG_VERSION=4.1
TERMUX_PKG_REVISION=2
NASUX_PKG_SRCURL=http://t-sato.in.coocan.jp/xvkbd/xvkbd-${NASUX_PKG_VERSION}.tar.gz
NASUX_PKG_SHA256=952d07df0fe1e45286520b7c98b4fd00fd60dbf3e3e8ff61e12c259f76a3bef4
NASUX_PKG_DEPENDS="libx11, libxaw, libxmu, libxt, libxtst"
TERMUX_PKG_BUILD_DEPENDS="xorgproto"
NASUX_PKG_BUILD_IN_SRC=true
