NASUX_PKG_HOMEPAGE=https://www.kde.org/
NASUX_PKG_DESCRIPTION="Advanced configuration system (KDE)"
NASUX_PKG_LICENSE="LGPL-2.1"
NASUX_PKG_MAINTAINER="@nastech-ai"
NASUX_PKG_VERSION="5.116.0"
NASUX_PKG_SRCURL="https://download.kde.org/stable/frameworks/${NASUX_PKG_VERSION%.*}/kconfig-${NASUX_PKG_VERSION}.tar.xz"
NASUX_PKG_SHA256=2c5de3609273aa167a5c49be42470a3bf87d70fc8565ba6cee3717c00067470e
TERMUX_PKG_AUTO_UPDATE=false
NASUX_PKG_DEPENDS="libc++, qt5-qtbase"
TERMUX_PKG_BUILD_DEPENDS="extra-cmake-modules, qt5-qtbase-cross-tools, qt5-qttools-cross-tools"
