NASUX_PKG_HOMEPAGE=https://xcb.freedesktop.org/
NASUX_PKG_DESCRIPTION="Utility libraries for XC Binding - Convenience functions for the Render extension"
NASUX_PKG_LICENSE="HPND, MIT"
NASUX_PKG_MAINTAINER="@nastech-ai"
NASUX_PKG_VERSION=0.3.10
TERMUX_PKG_REVISION=1
NASUX_PKG_SRCURL=https://xcb.freedesktop.org/dist/xcb-util-renderutil-${NASUX_PKG_VERSION}.tar.xz
NASUX_PKG_SHA256=3e15d4f0e22d8ddbfbb9f5d77db43eacd7a304029bf25a6166cc63caa96d04ba
NASUX_PKG_DEPENDS="libxcb"
TERMUX_PKG_BUILD_DEPENDS="xorg-util-macros"
