NASUX_PKG_HOMEPAGE=https://github.com/imgflo/imgflo
NASUX_PKG_DESCRIPTION="HTTP image processing server & Flowhub.io compatible runtime"
NASUX_PKG_LICENSE="MIT"
NASUX_PKG_MAINTAINER="@nastech-ai"
NASUX_PKG_VERSION=0.4.2
TERMUX_PKG_REVISION=9
NASUX_PKG_SRCURL=https://github.com/imgflo/imgflo/archive/refs/tags/$NASUX_PKG_VERSION.tar.gz
NASUX_PKG_SHA256=4dd5fc9d34f3cfc294fd69a14d50ed5401abeb829132f1b1ac316e28223fc393
NASUX_PKG_DEPENDS="babl, gegl, glib, json-glib, libpng, libsoup"
NASUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_UPDATE_TAG_TYPE="newest-tag"
