NASUX_PKG_HOMEPAGE=https://www.gnome.org
NASUX_PKG_DESCRIPTION="Common development macros for GNOME"
NASUX_PKG_LICENSE="GPL-2.0"
NASUX_PKG_MAINTAINER="@nastech-ai"
NASUX_PKG_VERSION=3.18.0
NASUX_PKG_SRCURL=https://download.gnome.org/sources/gnome-common/${NASUX_PKG_VERSION%.*}/gnome-common-${NASUX_PKG_VERSION}.tar.xz
NASUX_PKG_SHA256=22569e370ae755e04527b76328befc4c73b62bfd4a572499fde116b8318af8cf
NASUX_PKG_DEPENDS="autoconf-archive, intltool, gtk-doc"
TERMUX_PKG_PLATFORM_INDEPENDENT=true
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="--with-autoconf-archive"
