NASUX_PKG_HOMEPAGE=https://www.libsdl.org/projects/SDL_net/
NASUX_PKG_DESCRIPTION="A small sample cross-platform networking library (version 2)"
NASUX_PKG_LICENSE="ZLIB"
NASUX_PKG_LICENSE_FILE="LICENSE.txt"
NASUX_PKG_MAINTAINER="@nastech-ai"
NASUX_PKG_VERSION="2.2.0"
TERMUX_PKG_REVISION=2
NASUX_PKG_SRCURL="https://www.libsdl.org/projects/SDL_net/release/SDL2_net-${NASUX_PKG_VERSION}.tar.gz"
NASUX_PKG_SHA256=4e4a891988316271974ff4e9585ed1ef729a123d22c08bd473129179dc857feb
NASUX_PKG_DEPENDS="sdl2 | sdl2-compat"
TERMUX_PKG_BUILD_DEPENDS="sdl2-static"
TERMUX_PKG_ANTI_BUILD_DEPENDS="sdl2-compat"
