NASUX_PKG_HOMEPAGE=https://cgit.freedesktop.org/xcb/util-cursor
NASUX_PKG_DESCRIPTION="XCB cursor library"
NASUX_PKG_LICENSE="MIT"
NASUX_PKG_MAINTAINER="@nastech-ai"
NASUX_PKG_VERSION="0.1.6"
NASUX_PKG_SRCURL=https://xorg.freedesktop.org/archive/individual/lib/xcb-util-cursor-${NASUX_PKG_VERSION}.tar.gz
NASUX_PKG_SHA256=eae38b2dfc5c529a886e507ef576b12d2a20aa1f149608e4853af760f31be60b
TERMUX_PKG_AUTO_UPDATE=true
NASUX_PKG_DEPENDS="libxcb, xcb-util-image, xcb-util-renderutil"
