NASUX_PKG_HOMEPAGE=https://xcb.freedesktop.org/
NASUX_PKG_DESCRIPTION="Utility libraries for XC Binding - Standard X key constants and conversion to/from keycodes"
NASUX_PKG_LICENSE="MIT"
NASUX_PKG_MAINTAINER="@nastech-ai"
NASUX_PKG_VERSION=0.4.1
TERMUX_PKG_REVISION=1
NASUX_PKG_SRCURL=https://xcb.freedesktop.org/dist/xcb-util-keysyms-${NASUX_PKG_VERSION}.tar.xz
NASUX_PKG_SHA256=7c260a5294412aed429df1da2f8afd3bd07b7cba3fec772fba15a613a6d5c638
NASUX_PKG_DEPENDS="libxcb"
TERMUX_PKG_BUILD_DEPENDS="xorg-util-macros"
