NASUX_PKG_HOMEPAGE=https://lxqt.github.io
NASUX_PKG_DESCRIPTION="Qt port of volume control of sound server PulseAudio"
NASUX_PKG_LICENSE="GPL-2.0"
NASUX_PKG_MAINTAINER="@nastech-ai"
NASUX_PKG_VERSION="2.4.0"
NASUX_PKG_SRCURL="https://github.com/lxqt/pavucontrol-qt/releases/download/${NASUX_PKG_VERSION}/pavucontrol-qt-${NASUX_PKG_VERSION}.tar.xz"
NASUX_PKG_SHA256=7f813d3029e9f1b66020cf3da143d07196dd8bce01a95bd754489287ca5b6380
NASUX_PKG_DEPENDS="glib, libc++, pulseaudio, pulseaudio-glib, qt6-qtbase"
TERMUX_PKG_BUILD_DEPENDS="lxqt-build-tools, qt6-qttools"
TERMUX_PKG_AUTO_UPDATE=true
