NASUX_PKG_HOMEPAGE=https://github.com/Airblader/xcb-util-xrm/
NASUX_PKG_DESCRIPTION="XCB utility functions for the X resource manager"
NASUX_PKG_LICENSE="MIT"
NASUX_PKG_MAINTAINER="@nastech-ai"
NASUX_PKG_VERSION=1.3
TERMUX_PKG_REVISION=28
NASUX_PKG_SRCURL=https://github.com/Airblader/xcb-util-xrm/releases/download/v${NASUX_PKG_VERSION}/xcb-util-xrm-${NASUX_PKG_VERSION}.tar.gz
NASUX_PKG_SHA256=0129f74c327ae65e2f4ad4002f300b4f02c9aff78c00997f1f1c5a430f922f34
NASUX_PKG_DEPENDS="libxcb, xcb-util"
TERMUX_PKG_BUILD_DEPENDS="libx11, xorgproto"
