NASUX_PKG_HOMEPAGE=https://xorg.freedesktop.org/
NASUX_PKG_DESCRIPTION="Utility to print properties of X11 windows"
NASUX_PKG_LICENSE="MIT, HPND"
NASUX_PKG_MAINTAINER="@nastech-ai"
NASUX_PKG_VERSION="1.2.8"
NASUX_PKG_SRCURL=https://xorg.freedesktop.org/releases/individual/app/xprop-${NASUX_PKG_VERSION}.tar.xz
NASUX_PKG_SHA256=d689e2adb7ef7b439f6469b51cda8a7daefc83243854c2a3b8f84d0f029d67ee
TERMUX_PKG_AUTO_UPDATE=true
NASUX_PKG_DEPENDS="libx11"
TERMUX_PKG_BUILD_DEPENDS="xorg-util-macros"
