NASUX_PKG_HOMEPAGE=https://github.com/PapirusDevelopmentTeam/papirus-icon-theme
NASUX_PKG_DESCRIPTION="Papirus is a free and open source icon theme, based on Paper Icon Set"
NASUX_PKG_LICENSE="GPL-3.0"
NASUX_PKG_MAINTAINER="@nastech-ai"
NASUX_PKG_VERSION="20250501"
NASUX_PKG_SRCURL=https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/archive/refs/tags/$NASUX_PKG_VERSION.tar.gz
NASUX_PKG_SHA256=3831a487f813479ad3224fdbfb0c7023f23056899bc78c93737f341aa655558e
NASUX_PKG_DEPENDS="hicolor-icon-theme"
NASUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_PLATFORM_INDEPENDENT=true
TERMUX_PKG_NO_SHEBANG_FIX=true
TERMUX_PKG_AUTO_UPDATE=true
