NASUX_PKG_HOMEPAGE=https://fcitx-im.org/
NASUX_PKG_DESCRIPTION="Fcitx Qt immodule & library"
NASUX_PKG_LICENSE="LGPL-2.1"
NASUX_PKG_MAINTAINER="@nastech-ai"
NASUX_PKG_VERSION="5.1.13"
NASUX_PKG_SRCURL=https://github.com/fcitx/fcitx5-qt/archive/refs/tags/${NASUX_PKG_VERSION}.tar.gz
NASUX_PKG_SHA256=74b2c43ca865ec9ede257bcd3bdadafc20f571900cb2440a4488335e4d4e91cc
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_UPDATE_TAG_TYPE="newest-tag"
NASUX_PKG_DEPENDS="fcitx5, libc++, libwayland, libx11, libxcb, libxkbcommon, qt6-qtbase"
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
-DCMAKE_INSTALL_QT6PLUGINDIR=lib/qt6/plugins
-DENABLE_TEST=OFF
-DENABLE_QT4=OFF
-DENABLE_QT5=OFF
-DENABLE_QT6=ON
-DENABLE_QT6_WAYLAND_WORKAROUND=ON
"
