NASUX_PKG_HOMEPAGE=https://xcb.freedesktop.org/
NASUX_PKG_DESCRIPTION="Utility libraries for XC Binding - client and window-manager helpers for ICCCM"
NASUX_PKG_LICENSE="MIT"
NASUX_PKG_MAINTAINER="@nastech-ai"
NASUX_PKG_VERSION=0.4.2
TERMUX_PKG_REVISION=1
NASUX_PKG_SRCURL=https://xcb.freedesktop.org/dist/xcb-util-wm-${NASUX_PKG_VERSION}.tar.xz
NASUX_PKG_SHA256=62c34e21d06264687faea7edbf63632c9f04d55e72114aa4a57bb95e4f888a0b
NASUX_PKG_DEPENDS="libxcb"
TERMUX_PKG_BUILD_DEPENDS="xorg-util-macros"
