NASUX_PKG_HOMEPAGE="https://github.com/lxqt/qtxdg-tools"
NASUX_PKG_DESCRIPTION="CLI tools for libqtxdg."
NASUX_PKG_LICENSE="LGPL-2.1"
NASUX_PKG_MAINTAINER="@nastech-ai"
NASUX_PKG_VERSION="4.4.0"
NASUX_PKG_SRCURL="https://github.com/lxqt/qtxdg-tools/releases/download/${NASUX_PKG_VERSION}/qtxdg-tools-${NASUX_PKG_VERSION}.tar.xz"
NASUX_PKG_SHA256=f21ba4308eac0effd417d910cc4916df7b6202aaeee777b51bb120f7abc6c5ac
NASUX_PKG_DEPENDS="libc++, libqtxdg, qt6-qtbase"
TERMUX_PKG_BUILD_DEPENDS="lxqt-build-tools, qt6-qttools"
TERMUX_PKG_AUTO_UPDATE=true
