NASUX_PKG_HOMEPAGE=https://xorg.freedesktop.org/
NASUX_PKG_DESCRIPTION="X.org void input driver"
NASUX_PKG_LICENSE="MIT"
NASUX_PKG_MAINTAINER="@nastech-ai"
NASUX_PKG_VERSION=1.4.2
TERMUX_PKG_REVISION=1
NASUX_PKG_SRCURL=https://xorg.freedesktop.org/releases/individual/driver/xf86-input-void-${NASUX_PKG_VERSION}.tar.xz
NASUX_PKG_SHA256=a211d8e21ce0e2ed8af5b8a2e8d4409d70c9c7e5ee528f5e6002ad279bf07885
NASUX_PKG_DEPENDS="xorg-server"
NASUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_NO_STATICSPLIT=true
