NASUX_PKG_HOMEPAGE="https://invent.kde.org/plasma/ocean-sound-theme"
NASUX_PKG_DESCRIPTION="Ocean Sound Theme for Plasma"
NASUX_PKG_LICENSE="LGPL-2.0-or-later"
NASUX_PKG_MAINTAINER="@nastech-ai"
NASUX_PKG_VERSION="6.6.5"
NASUX_PKG_SRCURL="https://download.kde.org/stable/plasma/${NASUX_PKG_VERSION}/ocean-sound-theme-${NASUX_PKG_VERSION}.tar.xz"
NASUX_PKG_SHA256=46b76160e6998e03b3990c669d6da166bd785da356841193eb548b35811dc6df
TERMUX_PKG_AUTO_UPDATE=true
NASUX_PKG_DEPENDS="libc++"
TERMUX_PKG_BUILD_DEPENDS="extra-cmake-modules, qt6-qtbase"
TERMUX_PKG_PLATFORM_INDEPENDENT=true
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
-DCMAKE_SYSTEM_NAME=Linux
-DKDE_INSTALL_QMLDIR=lib/qt6/qml
-DKDE_INSTALL_QTPLUGINDIR=lib/qt6/plugins
"
