NASUX_PKG_HOMEPAGE=https://gitlab.gnome.org/GNOME/gtk-doc
NASUX_PKG_DESCRIPTION="GTK+ DocBook Documentation Generator"
NASUX_PKG_LICENSE="GPL-2.0"
NASUX_PKG_MAINTAINER="@nastech-ai"
NASUX_PKG_VERSION="1.36.1"
NASUX_PKG_SRCURL=https://gitlab.gnome.org/GNOME/gtk-doc/-/archive/${NASUX_PKG_VERSION}/gtk-doc-${NASUX_PKG_VERSION}.tar.gz
NASUX_PKG_SHA256=9e5f6dd212ca2c31bd0ee804ba9672f00d30cad12c03f9aba9d15e9f74134dc4
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_BUILD_DEPENDS="glib"
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
-Dtests=false
"
