NASUX_PKG_HOMEPAGE=https://xorg.freedesktop.org/
NASUX_PKG_DESCRIPTION="Tab Window Manager for the X Window System"
NASUX_PKG_LICENSE="MIT, HPND"
NASUX_PKG_MAINTAINER="@nastech-ai"
NASUX_PKG_VERSION=1.0.13.1
NASUX_PKG_SRCURL=https://xorg.freedesktop.org/releases/individual/app/twm-${NASUX_PKG_VERSION}.tar.xz
NASUX_PKG_SHA256=a52534755aa8b492c884e52fa988bac84ab4d54641954679b9aaf08e323df2c5
NASUX_PKG_DEPENDS="libice, libsm, libx11, libxext, libxmu, libxrandr, libxt"
TERMUX_PKG_BUILD_DEPENDS="xorg-util-macros"
TERMUX_PKG_AUTO_UPDATE=true
