NASUX_PKG_HOMEPAGE=https://wiki.gnome.org/Accessibility
NASUX_PKG_DESCRIPTION="A python client library for the AT-SPI D-Bus accessibility infrastructure"
NASUX_PKG_LICENSE="LGPL-2.0, GPL-2.0"
NASUX_PKG_MAINTAINER="@nastech-ai"
NASUX_PKG_VERSION="2.58.2"
NASUX_PKG_SRCURL=https://download.gnome.org/sources/pyatspi/${NASUX_PKG_VERSION%.*}/pyatspi-${NASUX_PKG_VERSION}.tar.xz
NASUX_PKG_SHA256=24590e5b60fec8dfb59fcd27d2a90de7034060be318ca3f7770e0f984f1f94e2
TERMUX_PKG_AUTO_UPDATE=true
NASUX_PKG_DEPENDS="at-spi2-core, dbus, dbus-python, pygobject, python"
TERMUX_PKG_SETUP_PYTHON=true
TERMUX_PKG_PLATFORM_INDEPENDENT=true
