NASUX_PKG_HOMEPAGE=https://xorg.freedesktop.org/
NASUX_PKG_DESCRIPTION="X.Org authorization settings program"
NASUX_PKG_LICENSE="MIT"
NASUX_PKG_MAINTAINER="@nastech-ai"
NASUX_PKG_VERSION="1.1.5"
NASUX_PKG_SRCURL=https://xorg.freedesktop.org/releases/individual/app/xauth-${NASUX_PKG_VERSION}.tar.xz
NASUX_PKG_SHA256=a4000e2f441facebf569026bedecc23ba262cc6927be52070abe0002625cfbe0
TERMUX_PKG_AUTO_UPDATE=true
NASUX_PKG_DEPENDS="libx11, libxau, libxext, libxmu"
TERMUX_PKG_BUILD_DEPENDS="xorg-util-macros"
