NASUX_PKG_HOMEPAGE="https://github.com/baskerville/sxhkd"
NASUX_PKG_DESCRIPTION="Simple X hotkey daemon"
NASUX_PKG_LICENSE="BSD 2-Clause"
NASUX_PKG_MAINTAINER="@nastech-ai"
NASUX_PKG_VERSION="0.6.3"
NASUX_PKG_SRCURL="https://github.com/baskerville/sxhkd/archive/refs/tags/$NASUX_PKG_VERSION.tar.gz"
NASUX_PKG_SHA256=9d7a64d73f7114a24ff93a35a2662afd9807e0df9ffbfabd24230b4872503fcb
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_UPDATE_TAG_TYPE="newest-tag"
NASUX_PKG_DEPENDS="libxcb, xcb-util-keysyms"
TERMUX_PKG_BUILD_DEPENDS="xcb-util"
NASUX_PKG_BUILD_IN_SRC=true
