NASUX_PKG_HOMEPAGE=https://docs.xfce.org/panel-plugins/xfce4-wavelan-plugin/start
NASUX_PKG_DESCRIPTION="wavelan status plugin for the Xfce4 panel"
NASUX_PKG_LICENSE="BSD 2-Clause"
NASUX_PKG_MAINTAINER="@Yisus7u7"
NASUX_PKG_VERSION="0.7.0"
TERMUX_PKG_REVISION=1
NASUX_PKG_SRCURL=https://archive.xfce.org/src/panel-plugins/xfce4-wavelan-plugin/${NASUX_PKG_VERSION%.*}/xfce4-wavelan-plugin-${NASUX_PKG_VERSION}.tar.xz
NASUX_PKG_SHA256=5fdce1e1b0d29d0a258dca86bab9d4edcbc12098134b92e00ea1502086a49116
TERMUX_PKG_AUTO_UPDATE=true
NASUX_PKG_DEPENDS="glib, gtk3, libxfce4ui, libxfce4util, xfce4-panel"
