NASUX_PKG_HOMEPAGE=https://www.kde.org/
NASUX_PKG_DESCRIPTION="Extra CMake modules (KDE)"
NASUX_PKG_LICENSE="BSD 3-Clause"
NASUX_PKG_LICENSE_FILE="LICENSES/BSD-3-Clause.txt"
NASUX_PKG_MAINTAINER="@nastech-ai"
NASUX_PKG_VERSION="6.27.0"
NASUX_PKG_SRCURL="https://download.kde.org/stable/frameworks/${NASUX_PKG_VERSION%.*}/extra-cmake-modules-${NASUX_PKG_VERSION}.tar.xz"
NASUX_PKG_SHA256=f3b5af578017a6a0f127fb1c31609db2e4f016e99b900d5a11f6ffb6c55006a3
TERMUX_PKG_AUTO_UPDATE=true
NASUX_PKG_DEPENDS="cmake"
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
-DBUILD_HTML_DOCS=OFF
-DBUILD_QTHELP_DOCS=OFF
-DBUILD_TESTING=OFF
"
