name: Command Not Found Rebuild

on:
  schedule:
    - cron: "0 4 * * 0" # Runs at 04:00am UTC every Sunday
  workflow_dispatch:

permissions: {} # none

jobs:
  rebuild-command-not-found:
    permissions:
      issues: write
      contents: write
    if: github.repository == 'nastech-ai/NasUX-Packages'
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
          token: ${{ secrets.NASTECH_BOT_TOKEN }}
      - name: Revbump main/command-not-found
        env:
          GITHUB_TOKEN: ${{ secrets.NASTECH_BOT_TOKEN }}
        run: |
          git config --global user.name "NasTech Bot"
          git config --global user.email "nastech-bot@users.noreply.github.com"

          ./scripts/bin/revbump command-not-found
          git add .
          git commit -m "rebuild(main/command-not-found): to update database"
          git push
